### PR TITLE
make simple web client

### PR DESCRIPTION
**Pull request by jameslaneconkling**

### CODE REVIEW

**Comment by RRDuke** [comment]
I think you should remove the mapbox api key from the script.js file, no? Other than that it looks good to me

**Comment by jameslaneconkling** [comment]
it's the public key, so shouldn't be a problem (I think?).  Ultimately,
there's no real way to hide a key like that from a user, as it's required
to issue calls from the client to MapBox.  That being said, I have no idea
how it works--will look into it.

**Comment by RRDuke** [comment]
Ahh that makes sense. I just assumed it was a API key that you signed up for.

**Comment by jameslaneconkling** [comment]
it's tied to my MapBox account, so theoretically someone _could_ steal it
and start using it against my account's API limits.  It would be pretty
easy to swap it out for a new key, though.

As far as I know, there's nothing we can do to prevent users from seeing it
(and theoretically, from stealing it).

**Comment by timothyquach** [comment]
use tree-filter

**Comment by timothyquach** [comment]
usually you put  secrets into a module and export it. For example:
//secrets.js
exports =  {
  secret = 'My secret api key'
}

then use 
git filter-branch --force --index-filter \
'git rm --cached --ignore-unmatch secrets.js' \
--prune-empty --tag-name-filter cat -- --all

before every commit.

**Comment by timothyquach** [comment]
:-1: 
I can't thumbs up this without a rebase to remove the api key, since bots do actively scrape these things. remember what the seniors said about about AWS and it costing them $$$? I've personally been burned and almost banned from AWS for exposing my keys. That being said, I cant +1, but if we just want to move forward, I wouldn't mind if we just commit over this instead of rebasing.

**Comment by jameslaneconkling** [comment]
But it isn't possible to make a mapbox.js map w/o exposing the public key.
That, after all, is why they made it pubic.  This isn't an oversight,
really, but a deliberate part of the MapBox API.  See [here](https://www.mapbox.com/developers/api/).

AWS keys are different, because they live on the server and don't need to
be exposed to the client.  But the whole point of MapBox keys is that they
are shared amongst clients.  Or am I missing something?

**Comment by timothyquach** [comment]
I think you're right.
https://www.mapbox.com/help/sharing-access-token/
Guess I need to start reading up on api auth.
:+1:

**Comment by RRDuke** [comment]
Thanks for the FAQ link, James. That cleared it up completely for me. Merging now

**Pull request merged**
