### PR TITLE
039 server routing photos

### PR DESCRIPTION
**Pull request by RRDuke**
Same as last pull request but now includes Photos functionality.

### CODE REVIEW

**Comment by jameslaneconkling** [comment]
@RRDuke , sorry, I think the merge I just made of Tim's changes to the Photo and Physicals route has conflicts with this PR.  Can you resolve?

**Comment by RRDuke** [comment]
Rebased and committed. Should be good now?

**Comment by Arahir** [comment]
:+1:

**Comment by timothyquach** [comment]
:+1:

**Comment by jameslaneconkling** [comment]
I'm not yet 100% on this, but it looks like our routes can be simplified a bit by utilizing model associations--the whole reason we set up `has_many` and `belongs_to` relationships between Photos, Comments, Users, and Physicals.  E.g.

``` javascript
Physical.photos().fetchAll()
//rather than
Photo.where({physical_id: physicalId}).fetchAll()
```

See Bookshelf [documentation](http://bookshelfjs.org/#Model-relations) on associations, though [RoR's guide to it's `Active Record` ORM](http://guides.rubyonrails.org/association_basics.html) goes into more detail on the philosophy of ORM associations.

Doing it this way is fine for now.  I'll open up an issue and try to work on it today.

**Comment by jameslaneconkling** [comment]
...although, fuck, just realized this will be difficult, as we don't really have Physical models, thanks to the Bookshelf-PostGIS glitch.

**Pull request merged**
