### PR TITLE
Return all API requests as geojson with model associations

### PR DESCRIPTION
**Pull request by jameslaneconkling**
Alright, the training wheels have finally come off.  I was able to work around the bug in Bookshelf for all routes except for `POST /physical`.  Which means:
- all responses are formatted as geoJSON
- all GET responses include model association data
- no more silly raw SQL queries
- much more flexibility when running `select` queries against the database (but alas, not yet on `insert` statements)

**do not merge this until the pervious commit has been merged**

### CODE REVIEW

**Comment by jameslaneconkling** [comment]
So, besides some cleanup, the last major thing to do to the API is allow the `POST /physical` route to insert to multiple dbs.  Though we haven't really hashed out all the user interaction patterns, presumably a user might still need to POST two, and maybe three assets at once (a physical, a photo, and a comment).

**Comment by RRDuke** [comment]
:+1:

**Comment by jameslaneconkling** [comment]
Fucking finally, pinpointed the error with Bookshelf, which it turns out was incredibly minor issue where bookshelf failed to correctly serialize models to JSON in cases when the models were queried using Insert raw statements.

came up with a quick patch, which should wrap up the whole thing.

**Comment by timothyquach** [comment]
:+1:

**Pull request merged**
