### PR TITLE
Issue #45 - refactor to get user_id from token

### PR DESCRIPTION
**Pull request by RRDuke**
Turns out we had this functionality already built. Just wasn't implemented all the way.

### CODE REVIEW

**Comment by timothyquach** [comment]
:+1:  
var userId = req.user.id; //user is created on req by helpers.decode

I'm not sure what the interaction between multer and helpers.decode is. This will probably work, but if it doesn't, this might be a starting point in debugging.

**Comment by RRDuke** [comment]
Cool - My guess is that it will be OK because all helpers.decode does is attach the user object to the request

**Comment by RRDuke** [comment]
Added another commit to this - I noticed there was some doubled code

**Comment by timothyquach** [comment]
:+1:

**Pull request merged**
