### PR TITLE
set up GET /physical/id/:id to return related content, using model registry

### PR DESCRIPTION
**Pull request by jameslaneconkling**
NOTE: this changes the way models are required, e.g.

``` javascript
require('./physical')
// not
var Physical = require('./physical')
```

Also note, @timothyquach and @Arahir routes now return geoJSON from the GET /physical routes.  So, find the returned data in `data.features`, instead of (as it used to be, I think) `data.physicals`.

Associations/related content is only returned for the /physical/id/:id route.  I'll try to get it working for the other routes as well.  (though I'm not 100% that it will be possible to both parse db data into geoJSON with PostGIS _and_ use Bookshelf models, with the latter required to return associations)

### CODE REVIEW

**Comment by RRDuke** [comment]
Looks good to me. One additional thing that I think we're going to need is the ability for the client to know what id was assigned to a newly created physical. Is that something we'd now be able to implement?

**Comment by RRDuke** [comment]
Actually,

I'm not following the change from 

var Physical = require(...) to
Physical = require(...).

doesn't this just implicitly create a Physical variable in the global scope? Why is killing the var correct?

**Comment by jameslaneconkling** [comment]
> I'm not following the change from
> 
> var Physical = require(...) to
> Physical = require(...).

Actually, you pointed out a bug: there should be no variable assignment at all.  E.g.

``` javascript
require('./physical');
```

Just pushed up a fix.

This is used in tandem with the [model registry plugin](https://github.com/tgriesser/bookshelf/wiki/Plugin:-Model-Registry), which allows you to define circular dependencies while still guaranteeing that all modules are loaded by the time the script runs.  I.e. our `physicalController.js` requires the `physical.js` model, which requires `comment.js` and `photo.j`s models, which both in turn require the `physical.js` model.  Under normal Node dependency loading behavior, the `physical.js` model would not actually be loaded by the time `comment.js` and `photo.js` loaded, which was causing the following line in each model to fail:

``` javascript
  physical: function(){
    return this.belongsTo(Physical, 'physicals_id');
  }
```

No idea how it does it, but the module registry ensures that circular dependencies like that are fully loaded before they run.

> One additional thing that I think we're going to need is the ability for the client to know what id was assigned to a newly created physical. Is that something we'd now be able to implement?

Haven't double checked exactly what's returned, but that should be the responsibility of [this line](https://github.com/jameslaneconkling/CharismaticLupine/blob/orm/server/physicals/physicalController.js#L98).  I know Bookshelf inserts return the model (including it's id); not sure what knex inserts return, though I'm sure we could make it do what we need to.

**Comment by RRDuke** [comment]
Thats what I thought too, but that response object does not contain the id of the thing that was inserted. It looks like this

``` javascript
{ command: 'INSERT',
  rowCount: 1,
  oid: 0,
  rows: [],
  fields: [],
  _parsers: [],
  RowCtor: null,
  rowAsArray: false,
  _getTypeParser: [Function] }

```

A hacky way I thought about doing it would be to put 

``` javascript
knex.raw('SELECT *, ST_AsGeoJSON(geo) as geojson FROM physicals WHERE ST_DWithin( physicals.geo::geography, ST_SetSRID(ST_Point(' + x + ',' + y + '), 4326)::geography, ' + proximity + ' )')
      .then(function(results){
        var physicalsGeoJSON = _dbRows2GeoJSON(results.rows);
        console.log('Success on GET /physical/:location . Returned ' +  physicalsGeoJSON.length + ' results.');
        res.status(200).send(physicalsGeoJSON);
        next();
```

inside the add physical function (modified to select only the one at the precise location of the new physical). This, however, would get weird if there happened to be two physicals at the exact same point

**Comment by jameslaneconkling** [comment]
Hmmm, yeah, that could work (there's enough precision in the x/y
coordinates that duplicate points are unlikely).  But still, it's such an
obvious feature that I imagine there should be a more straightforward way
to expose it through knex.

...in fact, there must be, b/c Bookshelf does it.  I'll look into it.  We
can keep this pull request on hold I push up a fix.

**Comment by RRDuke** [comment]
Yeah bookshelf totally does it. That's actually my biggest concern with out
project right now because I know the client absolutely needs that info in
order to function. Existing physicals aren't an issue because that data is
available once you've selected one.

**Comment by jameslaneconkling** [comment]
alright, I figured out a fix:

``` javascript
    knex('physicals')
      .insert({ 'geo': knex.raw('ST_SetSRID( ST_Point(?, ?) , 4326)', [x, y]) })
      .returning([ 'id', knex.raw('ST_AsGeoJSON(geo) as geojson') ])
```

however, in the process, I figured out how to swap out our knex queries for Bookshelf queries, which are required for getting the related content (photos and comments).  So, now we get it all: API responses with properly parsed data that includes related content.

Will push all that up as a separate pull request.  This PR will need to be merged first.

**Comment by RRDuke** [comment]
awesome :+1:

**Comment by timothyquach** [comment]
:+1:

**Pull request merged**
